name: ci

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm test
